runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
- url: /.*
  script: main.app
  #login: required

env_variables:
  MODEL_NAME: 'wq_mleap-bundle-1.3.zip'
  ENDPOINT: '35.234.79.201:65327/transform'
